---
title: "CCFRP Angler Newsletter"
output: html_document
date: "2026-02-19"
---
```{r}
anews <- read_csv("hw_newsletter_dat.csv")

df_look <- anews %>%
  group_by(species) %>%
  count() %>%
  arrange(desc(n))

top10list <- c("BLU", "GPR", "OLV", "VER", "KLP", "LCD" ,"CPR", "BLA", "TRE" ,"YTL")

df_piecharts <- anews %>%
  filter(species %in% top10list) %>% 
  mutate(species = as.factor(species))
gear_type_fly <- df_piecharts %>% 
  filter(gear == "FLY") %>% 
  group_by(species, gear, site) %>% 
  summarise(count =n(), .groups = "drop")  
  
gear_type_bar <- df_piecharts %>% 
  filter(gear == "BAR") %>% 
  group_by(species, gear, site) %>% 
  summarise(count =n(), .groups = "drop") 
   
  
gear_type_bat <- df_piecharts %>% 
  filter(gear == "BAT") %>% 
  group_by(species, gear, site) %>% 
  summarise(count =n(), .groups = "drop") 
 
```
```{r}
gear_type_fly_m <- gear_type_fly %>% 
  filter(site == "MPA")
gear_type_fly_m %>% 
  mutate(count = as.factor(count))
plot1 <- ggplot (data = gear_type_fly_m, aes(x = gear, y = count, fill = species)) +
  geom_bar(stat = "identity") +
   scale_fill_manual(name = "Species", values = c("steelblue2", "darkgreen","darkred", "goldenrod3", "black", "thistle3", "darkslategrey","coral2", "yellow", "darkolivegreen3"))+
  coord_polar(theta = "y", start=0) +
  theme_void() +
  theme(
    legend.text = element_text(size = 8),
    legend.title = element_text(size = 9)
  ) +
  theme(
    legend.key.size = unit(0.4, "cm")
  )

```
```{r}
ggsave(plot = plot1, filename = "plot1.png", path = "~/Desktop/Winter 2026 Lab Meetings/Github/CCFRP_2026-1-", dpi = 1000, height = 6, width = 6)
```

```{r}
gear_type_fly_r <- gear_type_fly %>% 
  filter(site == "REF")
gear_type_fly_r %>% 
  mutate(count = as.factor(count))
plot2 <- ggplot (data = gear_type_fly_r, aes(x = gear, y = count, fill = species)) +
  geom_bar(stat = "identity") +
   scale_fill_manual(name = "Species", values = c("aquamarine2", "steelblue2" ,"darkred", "goldenrod3", "black", "thistle3", "darkslategrey","coral2", "yellow", "darkolivegreen3"))+
  coord_polar(theta = "y", start=0) +
  theme_void() +
  theme(
    legend.text = element_text(size = 8),
    legend.title = element_text(size = 9)
  ) +
  theme(
    legend.key.size = unit(0.4, "cm")
  )
```
```{r}
ggsave(plot = plot2, filename = "plot2.png", path = "~/Desktop/Winter 2026 Lab Meetings/Github/CCFRP_2026-1-", dpi = 1000, height = 6, width = 6)
```

```{r}
gear_type_bat_m <- gear_type_bat %>% 
  filter(site == "MPA")
gear_type_bat_m %>% 
  mutate(count = as.factor(count))
plot3 <- ggplot (data = gear_type_bat_m, aes(x = gear, y = count, fill = species)) +
  geom_bar(stat = "identity") +
   scale_fill_manual(name = "Species", values = c("steelblue2",  "darkgreen", "darkred", "goldenrod3", "black", "thistle3", "darkslategrey", "coral2", "yellow"))+
  coord_polar(theta = "y", start=0) +
  theme_void() +
  theme(
    legend.text = element_text(size = 8),
    legend.title = element_text(size = 9)
  ) +
  theme(
    legend.key.size = unit(0.4, "cm")
  )
```
```{r}
ggsave(plot = plot3, filename = "plot3.png", path = "~/Desktop/Winter 2026 Lab Meetings/Github/CCFRP_2026-1-", dpi = 1000, height = 6, width = 6)
```

```{r}
gear_type_bat_r <- gear_type_bat %>% 
  filter(site == "REF")
gear_type_bat_r %>% 
  mutate(count = as.factor(count))
plot4 <- ggplot (data = gear_type_bat_r, aes(x = gear, y = count, fill = species)) +
  geom_bar(stat = "identity") +
   scale_fill_manual(name = "Species", values = c("aquamarine2", "steelblue2", "darkgreen", "darkred", "goldenrod3", "black", "thistle3", "darkslategrey", "coral2", "darkolivegreen3", "yellow"))+
  coord_polar(theta = "y", start=0) +
  theme_void() +
  theme(
    legend.text = element_text(size = 8),
    legend.title = element_text(size = 9)
  ) +
  theme(
    legend.key.size = unit(0.4, "cm")
  )
```
```{r}
ggsave(plot = plot4, filename = "Bat_REF.png", path = "~/Desktop/Winter 2026 Lab Meetings/Github/CCFRP_2026-1-", dpi = 1000, height = 6, width = 6)
```

```{r}
gear_type_bar_m <- gear_type_bar %>% 
  filter(site == "MPA")
gear_type_bar_m %>% 
  mutate(count = as.factor(count))
plot5 <- ggplot (data = gear_type_bar_m, aes(x = gear, y = count, fill = species)) +
  geom_bar(stat = "identity") +
   scale_fill_manual(name = "Species", values = c("steelblue2",  "darkgreen", "darkred", "goldenrod3", "black", "thistle3", "darkslategrey", "coral2", "yellow"))+
  coord_polar(theta = "y", start=0) +
  theme_void() +
  theme(
    legend.text = element_text(size = 8),
    legend.title = element_text(size = 9)
  ) +
  theme(
    legend.key.size = unit(0.4, "cm")
  )
```
```{r}
ggsave(plot = plot5, filename = "Bar_MPA.png", path = "~/Desktop/Winter 2026 Lab Meetings/Github/CCFRP_2026-1-", dpi = 1000, height = 6, width = 6)
```

```{r}
gear_type_bar_r <- gear_type_bar %>% 
  filter(site == "REF")
gear_type_bar_r %>% 
  mutate(count = as.factor(count))
plot6 <- ggplot (data = gear_type_bar_r, aes(x = gear, y = count, fill = species)) +
  geom_bar(stat = "identity") +
   scale_fill_manual(name = "Species", values = c("aquamarine", "steelblue2",  "darkgreen", "darkred", "goldenrod3", "black", "thistle3", "darkslategrey", "coral2", "yellow"))+
  coord_polar(theta = "y", start=0) +
  theme_void() +
  theme(
    legend.text = element_text(size = 8),
    legend.title = element_text(size = 9)
  ) +
  theme(
    legend.key.size = unit(0.4, "cm")
  )
```
```{r}
ggsave(plot = plot6, filename = "Bar_REF.png", path = "~/Desktop/Winter 2026 Lab Meetings/Github/CCFRP_2026-1-", dpi = 1000, height = 6, width = 6)
```


```{r}
alldata <- df_piecharts %>% 
  group_by(species, gear, site) %>% 
  summarise(count =n(), .groups = "drop") 


alldata_1 <- alldata %>% 
  mutate(count = as.factor(count))
plot7 <- ggplot (data = alldata, aes(x = gear, y = count, fill = species)) +
  geom_bar(stat = "identity") +
   scale_fill_manual(name = "Species", values = c("aquamarine2","steelblue2", "darkgreen", "darkred", "goldenrod3", "black", "thistle3", "darkslategrey","coral2", "yellow","pink"), labels = c(
     "BLA" = "Black Rockfish", 
     "BLU" = "Blue Rockfish", 
     "CPR" ="Copper Rockfish", 
     "GPR" = "Gopher Rockfish",
     "KLP" = "Kelp Rockfish", 
     "LCD" = "Lingcod",
     "OLV" = "Olive Rockfish",
     "TRE" = "Tree Fish",
     "VER" = "Vermillion Rockfish", 
     "YTL" = "Yellow Tail Rockfish"
     )) +
  coord_polar(theta = "y", start=0) +
  theme_void() +
  theme(
    legend.text = element_text(size = 8),
    legend.title = element_text(size = 9)
  ) +
  theme(
    legend.key.size = unit(0.4, "cm")
  ) 
```
```{r}
ggsave(plot = plot7, filename = "legend.png", path = "~/Desktop/Winter 2026 Lab Meetings/Github/CCFRP_2026-1-", dpi = 1000, height = 6, width = 9)
```


